### ISSUE TITLE
Suggestion for plugin

### ISSUE THREAD

**Issue by RoyEarle** [samp-incognito/samp-dns-plugin#1]
Hello.

I don't know is it a good idea, but I would like to suggest distance check between IPs in this plugin.
I think it would be very useful.

**Comment by samp-incognito** [comment]
Distance check? You mean geolocation? There are lots of GeoIP scripts on the SA-MP forum that do that.

I'm not really updating this plugin anymore, to be honest (last update was years ago). All of it can just be replicated with the HTTP functions now anyway.
